### ISSUE TITLE
Create a login/signup system

### ISSUE THREAD

**Issue by SoarinSkySagar** [SoarinSkySagar/bitcoin-wallet#1]
Create a login/signup page such that the wallet identities are stored for each user

**Comment by PedroHenriqueW** [comment]
This is complicated. You have a design template?

**Comment by SoarinSkySagar** [comment]
No. I do not have a design template to work on. Or you can leave this issue as I am thinking of solving this one myself.

**Comment by PedroHenriqueW** [comment]
All right, you are better suited to take care of issue . Where do you intend to store user information?

**Comment by SoarinSkySagar** [comment]
In the firebase itself, I'm new to it and yet to learn a lot of the features but I hope I pull it off!
