### ISSUE TITLE
Project Descriptioin

### ISSUE THREAD

**Issue by akshaymundra** [SoarinSkySagar/bitcoin-wallet#5]
I saw your project and would like to contribute but I can't figure out what your project does so it will be good updating the projects readme file to describe this project.

### some suggestions
- Add the motive of this project
- what service it gives to the users

**Comment by SoarinSkySagar** [comment]
Do you want me to update the readme or are you implying that you want to contribute to the readme?
I can assign you the issue if you are implying the latter one.

**Comment by akshaymundra** [comment]
I was not able to understand this project so it would be better if you describe readme

**Comment by SoarinSkySagar** [comment]
@Akshay272003 it is basically a frontend project on bitcoin, which can generate keys, mnemonics and addresses + QR code for a wallet.

**Comment by SoarinSkySagar** [comment]
@PedroHenriqueW do you want to write the readme.md for this?

**Comment by PedroHenriqueW** [comment]
I believe that in the current situation you are the most suitable, because someone has to explain the reasen for creating the project, its purpose and what you hope it will be in the future

It would be interesting if you said what features you want the project to have

**Comment by PedroHenriqueW** [comment]
And complement with the technical part

**Comment by gnsaved** [comment]
Please I would like To writete the readme for you.
