### ISSUE TITLE
code improvement suggestion

### ISSUE THREAD

**Issue by PedroHenriqueW** [SoarinSkySagar/bitcoin-wallet#6]
Put the keyword "required" in the input
![Input-path](https://github.com/SoarinSkySagar/bitcoin-wallet/assets/96525548/86e13574-30ab-42bb-bf5c-bc00a2650623)

Remove the first path check
![validate-path](https://github.com/SoarinSkySagar/bitcoin-wallet/assets/96525548/e365d1db-da75-42d0-bb3e-4b153f6c578a)

I can't modify the code right now

**Comment by SoarinSkySagar** [comment]
Sure @PedroHenriqueW , you're free to create a PR whenever you can, no hurries.
also, be sure to fork the repo once more as the code has been changed and may cause merge conflicts.

**Comment by PedroHenriqueW** [comment]
All right. I'm new to contributing open source

**Comment by PedroHenriqueW** [comment]
I realized that the keyword "required" is unnecessary, because you don't use a form tag

In addition the regex expression already does the validation

I think the best would be "path.value >= 2" to check if the user put something after "m/"

Because currently the regex can accept "m"

**Comment by SoarinSkySagar** [comment]
yes, you are right about that. that makes more sense!
